site_name: PyWeek 34 {Team Name}
theme:
    name: material
    custom_dir: docs/overrides
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep orange
          accent: light blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep orange
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

    icon:
        repo: fontawesome/brands/github
    hljs_languages:
        - c#
    shortcuts:
        help: 191 # ?
        next: 78 # n
        previous: 80 # p
        search: 83 # s
extra:
    version:
        provider: mike
        default: stable
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/MrTanoshii/PyWeek-34
          name: Source Code Repo
        - icon: fontawesome/solid/book
          link: https://github.com/MrTanoshii/PyWeek-34/docs
          name: Docs Repo
repo_url: https://github.com/MrTanoshii/PyWeek-34
repo_name: Source Code Repo
markdown_extensions:
    - attr_list
    - def_list
    - md_in_html
    - pymdownx.tasklist:
          custom_checkbox: true
