from pathlib import Path

from src.towers import *


class TOWERS:
    BASEPATH = Path("src/towers/sprites")
    RADIUS_BG_COLOR = (255, 255, 255, 64)
    SELECTED_OUTLINE_COLOR = (255, 255, 255, 255)

    REMOVE_TOWER = {
        "radius": 0,
        "remove": True,
    }

    # Different tower types
    BASE_TOWER = {
        "name": "Tower.png",
        "label": "Base tower",
        "level": 0,
        "attack_cooldown_sec": 100,
        "gold_cost": 0,
        "research_cost": 0,
        "radius": 0,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 0,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
    }
    CANNON_TOWER = {
        "name": "Cannon.png",
        "label": "Cannon",
        "level": 0,
        "attack_cooldown_sec": 3.0,
        "gold_cost": 200,
        "research_cost": 0,
        "radius": 5,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 120,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Bullet_Cannon.png",
        "bullet_scale": 0.7,
    }
    CANNON2_TOWER = {
        "name": "Cannon2.png",
        "label": "Double Cannon",
        "level": 0,
        "attack_cooldown_sec": 1.5,
        "gold_cost": 750,
        "research_cost": 0,
        "radius": 9,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 120,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Bullet_Cannon.png",
        "bullet_scale": 0.7,
    }
    CANNON3_TOWER = {
        "name": "Cannon3.png",
        "label": "Heavy Cannon",
        "level": 0,
        "attack_cooldown_sec": 2.5,
        "gold_cost": 2200,
        "research_cost": 0,
        "radius": 16,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 500,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Bullet_Cannon.png",
        "bullet_scale": 0.7,
    }
    MG_TOWER = {
        "name": "MG.png",
        "label": "Machine Gun",
        "level": 0,
        "attack_cooldown_sec": 0.35,
        "gold_cost": 400,
        "research_cost": 0,
        "radius": 6,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 20,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 25,
        "bullet_type": "Bullet_MG.png",
    }
    MG_TOWER2 = {
        "name": "MG2.png",
        "label": "Poison Tower",
        "level": 0,
        "attack_cooldown_sec": 1.5,
        "gold_cost": 1500,
        "research_cost": 0,
        "radius": 5,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 20,
        "damage_splash": 0,
        "damage_poison": 250,
        "size_tiles": 2,
        "bullet_speed": 15,
        "bullet_type": "Bullet_MG.png",
    }
    MG_TOWER3 = {
        "name": "MG3.png",
        "label": "Heavy Machine Gun",
        "level": 0,
        "attack_cooldown_sec": 0.15,
        "gold_cost": 2000,
        "research_cost": 0,
        "radius": 8,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 25,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 30,
        "bullet_type": "Bullet_MG.png",
    }
    MISSILE = {
        "name": "Missile_Launcher.png",
        "label": "Slow Tower",
        "level": 0,
        "attack_cooldown_sec": 0.5,
        "gold_cost": 750,
        "research_cost": 0,
        "radius": 9,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 20,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 15,
        "bullet_type": "bullet_frost.png",
        "bullet_scale": 0.2,
        "slow": True,
    }

    MISSILE_OLD_2 = {
        "name": "Missile_Launcher2.png",
        "label": "Rocket Launcher",
        "level": 0,
        "attack_cooldown_sec": 6,
        "gold_cost": 1500,
        "research_cost": 0,
        "radius": 16,
        "radius_splash": 0,
        "damage_air": 16,
        "damage_ground": 1000,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Missile.png",
        "bullet_scale": 0.7,
    }
    MISSILE2 = {
        "name": "Missile_Launcher2.png",
        "label": "Rocket Launcher",
        "level": 0,
        "attack_cooldown_sec": 7,
        "gold_cost": 4200,
        "research_cost": 0,
        "radius": 24,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 3000,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Missile.png",
        "bullet_scale": 0.7,
    }
    MISSILE3 = {
        "name": "Missile_Launcher3.png",
        "label": "Heavy Rocket Launcher",
        "level": 0,
        "attack_cooldown_sec": 7,
        "gold_cost": 10000,
        "research_cost": 0,
        "radius": 24,
        "radius_splash": 0,
        "damage_air": 0,
        "damage_ground": 7500,
        "damage_splash": 0,
        "damage_poison": 0,
        "size_tiles": 2,
        "bullet_speed": 20,
        "bullet_type": "Missile.png",
        "bullet_scale": 0.7,
    }
    ALL_TOWERS = [
        BASE_TOWER,
        MG_TOWER,
        MG_TOWER3,
        CANNON_TOWER,
        CANNON2_TOWER,
        CANNON3_TOWER,
        MISSILE2,
        MISSILE3,
        MG_TOWER2,
        MISSILE,
    ]
