name: Deploy Docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.10

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          update-environment: false

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      - name: Build & Deploy
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
